// src/utils/openclaw.ts
import { APP_CONFIG } from '@/config';

export function generateOpenClawSkills = () => {
  const skills = {
    market: {
      name: 'market',
      description: 'Get real-time market data',
      handler: async (context: any) => {
        try {
          const indices = await fetchGlobalIndices();
          return {
            status: 'success',
            data: indices.map(i => ({
              symbol: i.symbol,
              name: i.name,
              price: i.price,
              change: i.changePercent
            }))
          };
        } catch (error) {
          return {
            status: 'error',
            message: 'Failed to fetch market data'
          };
        }
      }
    },
    news: {
      name: 'news',
      description: 'Get latest market news',
      handler: async (context: any) => {
        try {
          const news = await fetchMarketNews(context.lang || 'zh');
          return {
            status: 'success',
            data: news.articles.map(article => ({
              title: article.title,
              description: article.description,
              url: article.url,
              source: article.source.name
            }))
          };
        } catch (error) {
          return {
            status: 'error',
            message: 'Failed to fetch news'
          };
        }
      }
    }
  };

  // 生成OpenClaw技能文件
  const skillsContent = `// Generated by stock.chat
module.exports = ${JSON.stringify(skills, null, 2)}`;

  return skillsContent;
};